<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="classes" nsURI="urn:uuid:27aa178c-696e-4d7d-a9d6-8cb6a8899d8c/metamodel/classes"
    nsPrefix="classes">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eAnnotations source="emf.gen">
    <details key="basePackage" value="sma.hm"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDiagram">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ClassNamesUnique"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ClassNamesUnique" value="self.classes->isUnique(name)"/>
    </eAnnotations>
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true" eOpposite="#//Class/diagram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="AttributeReferenceNamesUnique PrimaryKeyInThisClass"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="AttributeReferenceNamesUnique" value="&#xA;&#x9;&#x9;&#x9;self.references->collect(name)->union(self.attributes->collect(name))->isUnique(t|t)"/>
      <details key="PrimaryKeyInThisClass" value="self._primary_key = null or self._primary_key.cls = self"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="tool.name" value="Class"/>
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="size" value="200,150"/>
      <details key="border.color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true" eOpposite="#//Attribute/cls">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" containment="true" eOpposite="#//Reference/cls"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//ClassDiagram" eOpposite="#//ClassDiagram/classes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="_primary_key" eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eAnnotations source="gmf.node">
      <details key="tool.name" value="Attribute"/>
      <details key="label" value="name,type"/>
      <details key="label.pattern" value="{0}:{1}"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="border.color" value="0,0,0"/>
      <details key="margin" value="1"/>
      <details key="size" value="180,20"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cls" lowerBound="1" eType="#//Class"
        eOpposite="#//Class/attributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eAnnotations source="gmf.link">
      <details key="tool.name" value="Reference"/>
      <details key="label" value="name"/>
      <details key="source" value="cls"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cls" lowerBound="1" eType="#//Class"
        eOpposite="#//Class/references"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="integer"/>
    <eLiterals name="float" value="1"/>
    <eLiterals name="string" value="2"/>
    <eLiterals name="datetime" value="3"/>
    <eLiterals name="bool" value="4"/>
  </eClassifiers>
</ecore:EPackage>
